config/routes.rb
Rails.application.routes.draw do

  resources :discusses
  resources :teachers
  devise_for :users
  get 'users/show'
  resources :subject_reviews
  resources :subjects
  resources :subject_files
#   root 'static_pages#home'
   root 'subjects#index'
  
#   get 'static_pages/home'
  # root 'static_pages#home'
  # root 'subject_files#index'
  
   get 'static_pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/discusses_controller.rb
class DiscussesController < ApplicationController
  before_action :set_discuss, only: [:show, :edit, :update, :destroy]

  # GET /discusses
  # GET /discusses.json
  def index
    @discusses = Discuss.all
  end

  # GET /discusses/1
  # GET /discusses/1.json
  def show
  end

  # GET /discusses/new
  def new
    @discuss = Discuss.new
  end

  # GET /discusses/1/edit
  def edit
  end

  # POST /discusses
  # POST /discusses.json
  def create
    @discuss = Discuss.new(discuss_params)

    respond_to do |format|
      if @discuss.save
        format.html { redirect_to @discuss, notice: 'Discuss was successfully created.' }
        format.json { render :show, status: :created, location: @discuss }
      else
        format.html { render :new }
        format.json { render json: @discuss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discusses/1
  # PATCH/PUT /discusses/1.json
  def update
    respond_to do |format|
      if @discuss.update(discuss_params)
        format.html { redirect_to @discuss, notice: 'Discuss was successfully updated.' }
        format.json { render :show, status: :ok, location: @discuss }
      else
        format.html { render :edit }
        format.json { render json: @discuss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discusses/1
  # DELETE /discusses/1.json
  def destroy
    @discuss.destroy
    respond_to do |format|
      format.html { redirect_to discusses_url, notice: 'Discuss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discuss
      @discuss = Discuss.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discuss_params
      params.require(:discuss).permit(:user_id, :content)
    end
end

app/helpers/discusses_helper.rb
module DiscussesHelper
end

app/views/discusses/_form.html.erb
<%= form_with(model: discuss, local: true) do |form| %>
  <% if discuss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discuss.errors.count, "error") %> prohibited this discuss from being saved:</h2>

      <ul>
        <% discuss.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :user_id %></strong>
    <%= form.number_field :user_id , class: 'form-control'%>
  </div>

  <div class="field">
    <strong><%= form.label :content %></strong>
    <%= form.text_area :content , class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-sm', style: 'width: 100%'%>
  </div>
<% end %>

app/views/discusses/edit.html.erb
<div class="container pt-3" style="max-width: 700px;">
    <h1>Editing Discusses</h1>
    <%= render 'form', discuss: @discuss %>

    <button type="button"  class="btn btn-primary btn-dark btn-sm " style="width: 100%; margin-top: 5px">
     <%= link_to 'Back Discusses', discusses_path, class: 'text-white' %>
    </button>
</div>

app/views/discusses/index.html.erb
<div class="container pt-2">
<div class="col-11">
  <p id="notice"><%= notice %></p>
  <div  style="float: left; with:70%">
    <h1>Discusses</h1>
  </div>
  <div style="with:30%; float: right; margin: 1% 8.5% 5px;">
    <button type="button" class="btn btn-primary" style="float: left">
      <span><%= link_to 'New Discuss', new_discuss_path, class: 'text-white' %></span>
    </button>
  </div>

  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>User ID</th>
        <th >Content</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @discusses.each do |discuss| %>
        <tr>
          <td><%= discuss.user_id %></td>
          <td><%= discuss.content %></td>
          <td>
            <%# <div class="btn-group text-white" > %>
              <%# <button type="button" class="btn btn-primary "><%= link_to 'Show', discuss_path(discuss), class: 'text-white' </button> %>
              <button type="button" class="btn btn-warning "><%= link_to 'Edit', edit_discuss_path(discuss), class: 'text-white' %></button>
              <button type="button" class="btn btn-primary btn-danger"><%= link_to 'Destroy', discuss, method: :delete, data: { confirm: 'Are you sure?' } , class: 'text-white'%></button>
              
            <%# </div> %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>
</div>

app/views/discusses/new.html.erb
<h1>New Discuss</h1>
<div class="container pt-3" style="max-width: 700px;">
  <%= render 'form', discuss: @discuss %>
  <%= link_to 'Back', discusses_path, class: "btn btn-warning" %>
</div>

app/views/discusses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @discuss.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @discuss.content %>
</p>

<%= link_to 'Edit', edit_discuss_path(@discuss) %> |
<%= link_to 'Back', discusses_path %>