config/routes.rb
Rails.application.routes.draw do

  resources :discusses
  resources :teachers
  devise_for :users
  get 'users/show'
  resources :subject_reviews
  resources :subjects
  resources :subject_files
#   root 'static_pages#home'
   root 'subjects#index'
  
#   get 'static_pages/home'
  # root 'static_pages#home'
  # root 'subject_files#index'
  
   get 'static_pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/subject_reviews_controller.rb
class SubjectReviewsController < ApplicationController
  before_action :set_subject_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /subject_reviews
  # GET /subject_reviews.json
  def index
    @subject_reviews = SubjectReview.all
  end

  # GET /subject_reviews/1
  # GET /subject_reviews/1.json
  def show
  end

  # GET /subject_reviews/new
  def new
    @subject_review = SubjectReview.new
  end

  # GET /subject_reviews/1/edit
  def edit
  end

  # POST /subject_reviews
  # POST /subject_reviews.json
  def create
    @subject_review = SubjectReview.new(subject_review_params)
    @subject_review.user_id=current_user.id

    respond_to do |format|
      if @subject_review.save
        # format.html { redirect_to @subject_review, notice: 'Subject review was successfully created.' }
         url = "/subjects/" + @subject_review.subject_id.to_s
        format.html { redirect_to url, notice: 'Subject review was successfully created.' }
        format.json { render :show, status: :created, location: @subject_review }
      else
        format.html { render :new }
        format.json { render json: @subject_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subject_reviews/1
  # PATCH/PUT /subject_reviews/1.json
  def update
    respond_to do |format|
      if @subject_review.update(subject_review_params)
        format.html { redirect_to @subject_review, notice: 'Subject review was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject_review }
      else
        format.html { render :edit }
        format.json { render json: @subject_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_reviews/1
  # DELETE /subject_reviews/1.json
  def destroy
    @subject_review.destroy
    respond_to do |format|
      format.html { redirect_to subject_reviews_url, notice: 'Subject review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject_review
      @subject_review = SubjectReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_review_params
      params.require(:subject_review).permit(:user_id, :subject_id, :review)
    end
end

app/helpers/subject_reviews_helper.rb
module SubjectReviewsHelper
end

app/views/subject_reviews/_form.html.erb
<%= form_with(model: subject_review, local: true) do |form| %>
  <% if subject_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject_review.errors.count, "error") %> prohibited this subject_review from being saved:</h2>

      <ul>
        <% subject_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.number_field :subject_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subject_reviews/edit.html.erb
<h1>Editing Subject Review</h1>

<%= render 'form', subject_review: @subject_review %>

<%= link_to 'Show', @subject_review %> |
<%= link_to 'Back', subject_reviews_path %>

app/views/subject_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subject Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Subject</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subject_reviews.each do |subject_review| %>
      <tr>
        <td><%= subject_review.user_id %></td>
        <td><%= subject_review.subject_id %></td>
        <td><%= subject_review.review %></td>
        <td><%= link_to 'Show', subject_review %></td>
        <td><%= link_to 'Edit', edit_subject_review_path(subject_review) %></td>
        <td><%= link_to 'Destroy', subject_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject Review', new_subject_review_path %>

app/views/subject_reviews/new.html.erb
<h1>New Subject Review</h1>

<%= render 'form', subject_review: @subject_review %>

<%= link_to 'Back', subject_reviews_path %>

app/views/subject_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @subject_review.user_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @subject_review.subject_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @subject_review.review %>
</p>

<%= link_to 'Edit', edit_subject_review_path(@subject_review) %> |
<%= link_to 'Back', subject_reviews_path %>