config/routes.rb
Rails.application.routes.draw do

  resources :discusses
  resources :teachers
  devise_for :users
  get 'users/show'
  resources :subject_reviews
  resources :subjects
  resources :subject_files
#   root 'static_pages#home'
   root 'subjects#index'
  
#   get 'static_pages/home'
  # root 'static_pages#home'
  # root 'subject_files#index'
  
   get 'static_pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :subject_review, -> { order "created_at DESC"}
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :check_login, only: [:new, :create, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all.page(params[:page]).per(5)
  end
  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject_review=SubjectReview.new
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)
    @subject.user_id = current_user.id if current_user
    
    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:subject_code, :subject_name, :number_of_credits, :Description)
    end
    def check_login
      if current_user.nil?
        redirect_to new_user_session_path, error: "Please log in first!"
      end
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :subject_code %></strong>
    <%= form.number_field :subject_code , class: 'form-control'%>
  </div>

  <div class="field">
    <strong><%= form.label :subject_name %></strong>
    <%= form.text_field :subject_name , class: 'form-control'%>
  </div>

  <div class="field">
    <strong><%= form.label :number_of_credits %></strong><br>
    <p><%= form.select :number_of_credits, ['1', '2','3','4','5','6','7','8','9','10'], class: 'form-control'%></p>
  </div>
  <div class="form-group">
    <strong><%= form.label :Description%></strong>
    <%= form.text_area(:Description, class: 'form-control') %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-sm', style: 'width: 100%'%>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<div class="container pt-3" style="max-width: 700px;">
    <h1>Editing Subject</h1>
    <%= render 'form', subject: @subject %>

    <button type="button"  class="btn btn-primary btn-dark btn-sm " style="width: 100%; margin-top: 5px">
     <%= link_to 'Back Subjects', subjects_path, class: 'text-white' %>
    </button>
</div>

app/views/subjects/index.html.erb
<div class="container pt-3">
<p id="notice"><%= notice %></p>
<div  style="float: left; with:70%">
  <h1>Subjects</h1>
</div>
<div style="with:30%; float: right; margin: 1% 8.3% 5px;">
  <button type="button" class="btn btn-primary" style="float: left">
    <span><%= link_to 'New Subject', new_subject_path, class: 'text-white'%></span>
  </button>
</div>


<table class="table">
  <thead class="thead-dark text-center">
    <tr>
      <th>Subject code</th>
      <th>Subject name</th>
      <th >Number of credits</th>
      <th>  </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td class="text-center"><%= subject.subject_code %></td>
        <td class="text-center"><%= link_to subject.subject_name, subject, class: 'text-dark' %></td>
        <td class="text-center"><%= subject.number_of_credits %></td>
      
        
        <td class="text-right">
          <%= link_to subject do %>
            <button type="button" class="btn btn-info"><i class="far fa-eye"></i></button>
          <% end %>
        </td>
        <td>
          <% if current_user != nil %>
            <% if current_user.id == subject.user_id %>
              <%= link_to edit_subject_path(subject) do %>
                <button type="button" class="btn btn-secondary"><i class="far fa-edit"></i></button>
              <% end %>
                    
              <%= link_to subject, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <button type="button" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    
  </tbody>
</table>
<%= paginate @subjects %>
<br>
</div>

app/views/subjects/new.html.erb
<div class="container pt-3" style="max-width: 700px;">
    <br>
    <h1>New Subject</h1>
    <br>
    <%= render 'form', subject: @subject %>
    
    <button type="button"  class="btn btn-primary btn-dark btn-sm " style="width: 100%; margin-top: 5px">
     <%= link_to 'Back Subjects', subjects_path, class: 'text-white' %>
    </button>
</div>

app/views/subjects/show.html.erb
<div class="container pt-3 x">
  
  <p id="notice"><%= notice %></p>

  <nav class="navbar navbar-expand-lg  ">
    <ul class="navbar-nav mr-auto justify-content-center">
      <li class="nav-item">
         <span class="nav-link"><h2><%= @subject.subject_name %></h2></span>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" >
      <li class="nav-item">
           <% if current_user != nil %>
            <% if current_user.id == @subject.user_id %>
              <%= link_to edit_subject_path(@subject) do %>
                <button type="button" class="btn btn-secondary"><i class="far fa-edit"></i></button>
              <% end %>
                    
              <%= link_to @subject, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <button type="button" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
              <% end %>
            <% end %>
          <% end %>
      </li>
    </ul>
  </nav>
  <hr>
  
  <div class="" style="margin-left: 5%">
    <table class="" >
       <tbody>
         <tr>
           <td><strong>Subject code:</strong></td>
           <td style="padding-left: 15px"><%= @subject.subject_code %></td>
          </tr>
          <tr>
            <td><strong>Number of credits:</strong></td>
            <td style="padding-left: 15px"><%= @subject.number_of_credits %></td>
          </tr>
       </tbody>
    </table>
    
    <strong>Description:</strong>
    <p style="margin: -2.3% 5% 1% 9%"><%= @subject.Description %></p>
    <br>
  

    <div class="row">
        <div class="col-2">
            <button type="button"  class="nav-link btn btn-dark btn-sm " style="width: 100px">
              <%= link_to 'Back', subjects_path, class: 'text-white' %>
            </button>
        </div>
        <div class="col-10">
            <button type="button"  class="nav-link btn btn-info btn-sm " style="width: 100px; float: right">
              <%= link_to "To File", subject_files_path(:subject => @subject.id), class: 'text-white' %>
            </button>
        </div>
        <div class="col-8"></div>
    </div>
   </div>
<hr>


<h2>Review From</h2>
 <%= form_with(model: @subject_review, local: true) do |form| %>
   <div class= "field">
     <%= form.text_area :review %>
     <%= form.hidden_field :subject_id, :value => @subject.id %>
   </div>
   <div class="actions">
     <%= form.submit %>
   </div>
 <% end %>
 
 
 <h2>Review List</h2>

     <ul>

       <% @subject.subject_review.each do |subject_review|%><br>
          <li  class="comment">
          <b><%= subject_review.user.name if subject_review.user%></b><br>
           <%= subject_review.review %>
           </li> 
           
        <% end %>
     </ul>
     
</div>
 </div>

<style>
    .comment{
        border: 1px solid #000;
        padding-left:5px;
        list-style : none;
        border-radius: 10px;
        padding-top: 5px;
        padding-botton: 5px;
        width: 800px;
    }
</style>