config/routes.rb
Rails.application.routes.draw do

  resources :discusses
  resources :teachers
  devise_for :users
  get 'users/show'
  resources :subject_reviews
  resources :subjects
  resources :subject_files
#   root 'static_pages#home'
   root 'subjects#index'
  
#   get 'static_pages/home'
  # root 'static_pages#home'
  # root 'subject_files#index'
  
   get 'static_pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
        has_one_attached :image
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:name, :age, :email, :subjects, :image)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :subjects %>
    <%= form.text_field :subjects %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<div class="container pt-3">
<p id="notice"><%= notice %></p>
<div  style="float: left; with:70%">
  <h1>Teachers</h1>
</div>
<div style="with:30%; float: right; margin: 1% 8.3% 5px;">
  <button type="button" class="btn btn-primary" style="float: left">
    <span><%= link_to 'New Teacher', new_teacher_path, class: 'text-white'%></span>
  </button>
</div>

<table class="table text-center">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Subjects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= link_to teacher.name, teacher, class: 'text-dark' %></td>
        <td><%= teacher.age %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.subjects %></td>
        
          <td>
          <div class="btn-group text-white" >
            <button type="button" class="btn btn-primary "><%= link_to 'Edit', edit_teacher_path(teacher), class: 'text-white' %></button>
            <button type="button" class="btn btn-primary btn-danger"><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } , class: 'text-white'%></button>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/teachers/new.html.erb
<div class="container pt-3" style="max-width: 700px;">
    <br>
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

 <button type="button"  class="btn btn-primary btn-dark btn-sm " style="width: 100%; margin-top: 5px">
     <%= link_to 'Back Teachers List', teachers_path, class: 'text-white' %>
    </button>
</div>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @teacher.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Subjects:</strong>
  <%= @teacher.subjects %>
</p>

<p>
  <% if @teacher.image.attached? %>
    <%= image_tag @teacher.image %>
  <% end %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>